wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.21
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.51.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745727376.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 98
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 98
      3:
      - 13
      - 23
      4: 3.9.21
      5: 0.16.5
      6: 4.51.3
      8:
      - 5
      13: linux-x86_64
